services:
  - type: web
    name: guidecho-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000  # Render will override this anyway, but it's good practice
